### PR TITLE
updated CSS

### PR DESCRIPTION
**Pull request by hitomipupil**

### CODE REVIEW

**Comment by puemos** [comment]
I really like the new design!

**Just two things:**

| Item | Image |
|:--------:|--------|
| Bug: When the page first loads, the inputs are blank. | image |
| Enhancement: Maybe you can align the inputs and captions? | image |

**Comment by hitomipupil** [comment]
- Filled the inputs(color, column and row) with values
- Aligned the labels and the inputs
- Added hover effect on the reset button

**Comment by puemos** [comment]
Fantastic, one last thing: it might be better to change from "click" to "mousedown" to make the experience more snappy :)

https://github.com/hitomipupil/pixel-editor/blob/updateCSS/src/index.js#L61

**Comment by hitomipupil** [comment]
- changed event type from click to mousedown for grids. yes it is more intuitive :)

**Review by puemos — APPROVED** [review]

**Pull request merged**
